version: '3.9'

services:
  ###########################
  #   traefik container
  ###########################
  traefik:
    # pull the official v2 Traefik docker image
    image: 'traefik:v2.9'
    command:
      # enable Docker in Traefik, so that it reads labels from Docker services
      - '--providers.docker=true'
      # do not expose all containers unless explicitly told so
      - '--providers.docker.exposedbydefault=false'
      # traefik will listen to incoming request on the port 8088 (HTTP)
      - '--entrypoints.web.address=:8088'
    ports:
      - '8088:8088'
    volumes:
      # add Docker as a mounted volume, so that Traefik can read the labels of other services
      - '/var/run/docker.sock:/var/run/docker.sock:ro'

  ###########################
  #   client container
  ###########################
  client:
    build:
      context: ./client
      dockerfile: Dockerfile-prod
    labels:
      # explicitly tell Traefik to expose this container
      - 'traefik.enable=true'
      # specify the rule used to match a request to this service
      - 'traefik.http.routers.client.rule=Host(`211.178.39.246`)'
      # allow request only from the predefined entry point named "web"
      - 'traefik.http.routers.client.entrypoints=web'
      # set port the container listens to
      - 'traefik.http.services.client.loadbalancer.server.port=3000'
