version: '3.9'

services:
  ###########################
  #   client container
  ###########################
  client:
    build:
      context: ./client
      dockerfile: Dockerfile-dev
    command: npm run dev
    volumes:
      # HOST_PATH:CONTAINER_PATH:MODE
      - ./client:/client:consistent
    ports:
      - '3000:3000'
