version: '3.9'

services:
  ###########################
  #   traefik container
  ###########################
  traefik:
    # pull the official v2 Traefik docker image
    image: 'traefik:v2.9'
    command:
      # enable Docker in Traefik, so that it reads labels from Docker services
      - '--providers.docker=true'
      # do not expose all containers unless explicitly told so
      - '--providers.docker.exposedbydefault=false'
      # traefik will listen to incoming request on the port 8088 (HTTP)
      - '--entrypoints.web.address=:8088'
      # add a constraint to only use services with the label "custom.label=satellite"
      - '--providers.docker.constraints=Label(`custom.label`, `satellite`)'
      - --log.level=INFO
    ports:
      - '8088:8088'
    volumes:
      # add Docker as a mounted volume, so that Traefik can read the labels of other services
      - '/var/run/docker.sock:/var/run/docker.sock:ro'

  ###########################
  #   client container
  ###########################
  client:
    build:
      context: ./client
      dockerfile: Dockerfile-prod
    labels:
      # explicitly tell Traefik to expose this container
      - 'traefik.enable=true'
      # specify the rule used to match a request to this service
      - 'traefik.http.routers.client.rule=Host(`211.178.39.246`)'
      # allow request only from the predefined entry point named "web"
      - 'traefik.http.routers.client.entrypoints=web'
      # set port the container listens to
      - 'traefik.http.services.client.loadbalancer.server.port=3000'
      # Traefik will only use services with this label
      - 'custom.label=satellite'

  ###########################
  #   server container
  ###########################
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: hypercorn app.api.server:app --workers 4 --worker-class trio --bind 0.0.0.0:8000
    volumes:
      # hostPath:containerPath:mode
      - ./server:/server:consistent
    labels:
      # explicitly tell Traefik to expose this container
      - 'traefik.enable=true'
      # specify the rule used to match a request to this service
      - 'traefik.http.routers.server.rule=Host(`211.178.39.246`) && PathPrefix(`/api`)'
      # allow request only from the predefined entry point named "web"
      - 'traefik.http.routers.server.entrypoints=web'
      # set port the container listens to
      - 'traefik.http.services.server.loadbalancer.server.port=8000'
      - 'custom.label=satellite'
